config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "books#index"
  resources :books do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :reviews, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :likes, dependent: :destroy

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments
    @comment = Comment.new
    @likes = Like.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user = current_user

    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.user = current_user
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_book, only: %i[new create edit update]

  def new
    @comment = @book.comments.new
  end

  def create
    @comment = @book.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to book_path(@book), notice: 'Review added successfully.'
    else
      render :new
    end
  end

  def edit
    @comment = @book.comments.find(params[:id])
  end

  def update
    @comment = @book.comments.find(params[:id])
    @comment.user = current_user

    if @comment.update(comment_params)
      redirect_to book_path(@book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.user = current_user
    if @comment.destroy
      redirect_to book_comments_path(@comment.book), notice: 'Review deleted successfully.'
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:reviews)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @like = @book.likes.create(user: current_user)

    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @like = @book.likes.find(params[:id])

    if @like.destroy
      redirect_to book_path(@book), notice: 'Like removed successfully.'
    else
      redirect_to book_path(@book), alert: 'Unable to remove like.'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/books/_delete-button.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class='h-6 ml-2' viewBox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>

app/views/books/_edit-button.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class='h-6' viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152L0 424c0 48.6 39.4 88 88 88l272 0c48.6 0 88-39.4 88-88l0-112c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 112c0 22.1-17.9 40-40 40L88 464c-22.1 0-40-17.9-40-40l0-272c0-22.1 17.9-40 40-40l112 0c13.3 0 24-10.7 24-24s-10.7-24-24-24L88 64z"/></svg>

app/views/books/_form.html.erb
<h1 class="text-3xl font-bold mb-6">New Product</h1>

<%= form_with model: @book, class: "space-y-4 bg-white p-6 shadow-lg rounded-lg" do |form| %>
  <div class="flex flex-col">
    <%= form.label :title, class: "text-gray-700 font-semibold" %>
    <%= form.text_field :title, class: "mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-300" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :body, class: "text-gray-700 font-semibold" %>
    <%= form.text_field :body, class: "mt-1 p-2 border border-gray-300 rounded-lg focus:ring focus:ring-blue-300" %>
  </div>

  <div>
    <%= form.submit "Create Book", class: "bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition" %>
  </div>
<% end %>

app/views/books/_like-button.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class='h-6' viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M323.8 34.8c-38.2-10.9-78.1 11.2-89 49.4l-5.7 20c-3.7 13-10.4 25-19.5 35l-51.3 56.4c-8.9 9.8-8.2 25 1.6 33.9s25 8.2 33.9-1.6l51.3-56.4c14.1-15.5 24.4-34 30.1-54.1l5.7-20c3.6-12.7 16.9-20.1 29.7-16.5s20.1 16.9 16.5 29.7l-5.7 20c-5.7 19.9-14.7 38.7-26.6 55.5c-5.2 7.3-5.8 16.9-1.7 24.9s12.3 13 21.3 13L448 224c8.8 0 16 7.2 16 16c0 6.8-4.3 12.7-10.4 15c-7.4 2.8-13 9-14.9 16.7s.1 15.8 5.3 21.7c2.5 2.8 4 6.5 4 10.6c0 7.8-5.6 14.3-13 15.7c-8.2 1.6-15.1 7.3-18 15.2s-1.6 16.7 3.6 23.3c2.1 2.7 3.4 6.1 3.4 9.9c0 6.7-4.2 12.6-10.2 14.9c-11.5 4.5-17.7 16.9-14.4 28.8c.4 1.3 .6 2.8 .6 4.3c0 8.8-7.2 16-16 16l-97.5 0c-12.6 0-25-3.7-35.5-10.7l-61.7-41.1c-11-7.4-25.9-4.4-33.3 6.7s-4.4 25.9 6.7 33.3l61.7 41.1c18.4 12.3 40 18.8 62.1 18.8l97.5 0c34.7 0 62.9-27.6 64-62c14.6-11.7 24-29.7 24-50c0-4.5-.5-8.8-1.3-13c15.4-11.7 25.3-30.2 25.3-51c0-6.5-1-12.8-2.8-18.7C504.8 273.7 512 257.7 512 240c0-35.3-28.6-64-64-64l-92.3 0c4.7-10.4 8.7-21.2 11.8-32.2l5.7-20c10.9-38.2-11.2-78.1-49.4-89zM32 192c-17.7 0-32 14.3-32 32L0 448c0 17.7 14.3 32 32 32l64 0c17.7 0 32-14.3 32-32l0-224c0-17.7-14.3-32-32-32l-64 0z"/></svg>

app/views/books/_liked-button.html.erb
  <svg xmlns="http://www.w3.org/2000/svg" class='h-6' viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M313.4 32.9c26 5.2 42.9 30.5 37.7 56.5l-2.3 11.4c-5.3 26.7-15.1 52.1-28.8 75.2l144 0c26.5 0 48 21.5 48 48c0 18.5-10.5 34.6-25.9 42.6C497 275.4 504 288.9 504 304c0 23.4-16.8 42.9-38.9 47.1c4.4 7.3 6.9 15.8 6.9 24.9c0 21.3-13.9 39.4-33.1 45.6c.7 3.3 1.1 6.8 1.1 10.4c0 26.5-21.5 48-48 48l-97.5 0c-19 0-37.5-5.6-53.3-16.1l-38.5-25.7C176 420.4 160 390.4 160 358.3l0-38.3 0-48 0-24.9c0-29.2 13.3-56.7 36-75l7.4-5.9c26.5-21.2 44.6-51 51.2-84.2l2.3-11.4c5.2-26 30.5-42.9 56.5-37.7zM32 192l64 0c17.7 0 32 14.3 32 32l0 224c0 17.7-14.3 32-32 32l-64 0c-17.7 0-32-14.3-32-32L0 224c0-17.7 14.3-32 32-32z"/></svg>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<h1 class="text-2xl">Books!</h1>
<%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>


<div class="mt-4 mb-4">
  <%= link_to 'Add a book', new_book_path, class: 'border rounded-md bg-blue-300 py-1 px-3' %> <br>
</div>

<ul>
  <% @books.each do |book| %>
    <li class="mt-2"><%= link_to book.title, book_path(book) %></li>
  <% end %>
</ul>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<%= link_to 'Home', root_path, class:'border rounded-md bg-blue-300 py-1 px-3' %>
<div class='text-lg font-bold'>
  <%= @book.title %>

  <div class="flex mt-2">
    <% if @book.user.email == current_user.email %>
      <%= link_to edit_book_path(@book) do %>
        <%= render 'edit-button' %>
      <% end %>
      <%= button_to @book, method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
        <%= render 'delete-button' %>
      <% end %>
    <% end %>
  </div>
</div>

<p class="text-sm text-gray-800 mt-3">
  <%= @book.body %>
</p>

<%# post user %>
<p class="text-sm text-gray-800 mt-3">
  posted by: <%= @book.user.email %>
</p>

<%# likes %>
<p>
  <% if current_user.likes.exists?(book: @book) %>
    <% like = current_user.likes.find_by(book: @book) %>
    <%= button_to book_like_path(@book, like), method: :delete, class:'cursor-pointer' do %>
    <%= render 'liked-button' %>
  <% end %>
  <% else %>
  <%= button_to book_likes_path(@book), method: :post, class:'cursor-pointer' do %>
    <%= render 'like-button' %>
  <% end %>
  <% end %>
  <%= pluralize(@book.likes.count, 'like') %>
</p>

<%# reviews %>
<%= render 'comments/index' %>

app/views/comments/_delete-button.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class='h-3 ml-2' viewBox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>

app/views/comments/_edit-button.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class='h-3' viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152L0 424c0 48.6 39.4 88 88 88l272 0c48.6 0 88-39.4 88-88l0-112c0-13.3-10.7-24-24-24s-24 10.7-24 24l0 112c0 22.1-17.9 40-40 40L88 464c-22.1 0-40-17.9-40-40l0-272c0-22.1 17.9-40 40-40l112 0c13.3 0 24-10.7 24-24s-10.7-24-24-24L88 64z"/></svg>

app/views/comments/_form.html.erb
<%= form_with(model: [ @book, @comment ], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation" class="bg-red-500 text-white p-4 rounded mb-4">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4 mt-3">
    Add a review:
    <%#= form.label :reviews, class: 'block text-lg font-semibold mb-2' %>
    <%= form.text_area :reviews, required: true, class: 'w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none' %>
  </div>

  <div class="mb-4">
    <%= form.submit 'Add Review', class: 'bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% if @comments.count > 0 %>
  <h1 class="mt-3">Reviews:</h1>
<% end %>

<div class="text-sm text-gray-600">
  <% @comments.each do |comment| %>
    <p><%= comment.user.email %>:</p>
    <div class="flex">
      <p class='mr-3'><%= comment.reviews %></p>
      <% if comment.user.email == current_user.email  %>
        <%= link_to edit_book_comment_path(comment.book, comment)  do %>
          <%= render 'edit-button' %>
        <% end %>
        <%= button_to book_comment_path(comment.book, comment), method: :delete do %>
          <%= render 'delete-button' %>
        <% end %>
      <% end %>
    </div>

  <% end %>
</div>

<div>
  <%= render 'comments/form', book: @book, comment: @comment %>
</div>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-5 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/likes/new.html.erb
<%= render '../books/_liked-button.html.erb' %>